"""crear_tabla_tool_audit_logs

Revision ID: 114a376ae4e2
Revises: 90b7e1cfbd10
Create Date: 2026-07-03 23:36:05.594700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '114a376ae4e2'
down_revision: Union[str, Sequence[str], None] = '90b7e1cfbd10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
