"""add_jitsi_fields_to_appointment

Revision ID: 16c6dffeaf93
Revises: 2247e8277fda
Create Date: 2026-06-19 22:07:24.330293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


from sqlalchemy.engine import reflection

# revision identifiers, used by Alembic.
revision: str = '16c6dffeaf93'
down_revision: Union[str, Sequence[str], None] = '2247e8277fda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspect_obj = reflection.Inspector.from_engine(bind)
    tables = inspect_obj.get_table_names()

    if 'appointments' in tables:
        columns = [c['name'] for c in inspect_obj.get_columns('appointments')]
        if 'jitsi_room_name' not in columns:
            op.add_column('appointments', sa.Column('jitsi_room_name', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True))
        if 'jitsi_recording_cid' not in columns:
            op.add_column('appointments', sa.Column('jitsi_recording_cid', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True))
        if 'jitsi_transcription_cid' not in columns:
            op.add_column('appointments', sa.Column('jitsi_transcription_cid', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True))
        if 'declaration_text' not in columns:
            op.add_column('appointments', sa.Column('declaration_text', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspect_obj = reflection.Inspector.from_engine(bind)
    tables = inspect_obj.get_table_names()

    if 'appointments' in tables:
        columns = [c['name'] for c in inspect_obj.get_columns('appointments')]
        if 'declaration_text' in columns:
            op.drop_column('appointments', 'declaration_text')
        if 'jitsi_transcription_cid' in columns:
            op.drop_column('appointments', 'jitsi_transcription_cid')
        if 'jitsi_recording_cid' in columns:
            op.drop_column('appointments', 'jitsi_recording_cid')
        if 'jitsi_room_name' in columns:
            op.drop_column('appointments', 'jitsi_room_name')
    # ### end Alembic commands ###
