"""add_legal_knowledge_chunks_table

Revision ID: 2247e8277fda
Revises: 802d067255a8
Create Date: 2026-06-13 18:35:44.134277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector


from sqlalchemy.engine import reflection

# revision identifiers, used by Alembic.
revision: str = '2247e8277fda'
down_revision: Union[str, Sequence[str], None] = '802d067255a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspect_obj = reflection.Inspector.from_engine(bind)
    tables = inspect_obj.get_table_names()

    if 'legal_knowledge_chunks' not in tables:
        op.create_table('legal_knowledge_chunks',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('citation', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=3072), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_legal_knowledge_chunks_category'), 'legal_knowledge_chunks', ['category'], unique=False)
        op.create_index(op.f('ix_legal_knowledge_chunks_citation'), 'legal_knowledge_chunks', ['citation'], unique=False)
        op.create_index(op.f('ix_legal_knowledge_chunks_source'), 'legal_knowledge_chunks', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspect_obj = reflection.Inspector.from_engine(bind)
    tables = inspect_obj.get_table_names()

    if 'legal_knowledge_chunks' in tables:
        op.drop_index(op.f('ix_legal_knowledge_chunks_source'), table_name='legal_knowledge_chunks')
        op.drop_index(op.f('ix_legal_knowledge_chunks_citation'), table_name='legal_knowledge_chunks')
        op.drop_index(op.f('ix_legal_knowledge_chunks_category'), table_name='legal_knowledge_chunks')
        op.drop_table('legal_knowledge_chunks')
    # ### end Alembic commands ###
