"""add_missing_user_fields

Revision ID: 802d067255a8
Revises: 95e503014105
Create Date: 2026-06-05 22:58:33.436264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


from sqlalchemy.engine import reflection

# revision identifiers, used by Alembic.
revision: str = '802d067255a8'
down_revision: Union[str, Sequence[str], None] = '95e503014105'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspect_obj = reflection.Inspector.from_engine(bind)
    tables = inspect_obj.get_table_names()

    if 'signature_requests' not in tables:
        op.create_table('signature_requests',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('document_filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('signers', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('expiration', sa.DateTime(), nullable=False),
        sa.Column('signed_document_cid', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('sha256_signed', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_signature_requests_document_filename'), 'signature_requests', ['document_filename'], unique=False)
        op.create_index(op.f('ix_signature_requests_expiration'), 'signature_requests', ['expiration'], unique=False)
        op.create_index(op.f('ix_signature_requests_sha256_signed'), 'signature_requests', ['sha256_signed'], unique=False)
        op.create_index(op.f('ix_signature_requests_signed_document_cid'), 'signature_requests', ['signed_document_cid'], unique=False)
        op.create_index(op.f('ix_signature_requests_status'), 'signature_requests', ['status'], unique=False)
        op.create_index(op.f('ix_signature_requests_user_id'), 'signature_requests', ['user_id'], unique=False)
    
    if 'users' in tables:
        columns = [c['name'] for c in inspect_obj.get_columns('users')]
        if 'phone' not in columns:
            op.add_column('users', sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        if 'notification_preferences' not in columns:
            op.add_column('users', sa.Column('notification_preferences', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspect_obj = reflection.Inspector.from_engine(bind)
    tables = inspect_obj.get_table_names()

    if 'users' in tables:
        columns = [c['name'] for c in inspect_obj.get_columns('users')]
        if 'notification_preferences' in columns:
            op.drop_column('users', 'notification_preferences')
        if 'phone' in columns:
            op.drop_column('users', 'phone')

    if 'signature_requests' in tables:
        op.drop_index(op.f('ix_signature_requests_user_id'), table_name='signature_requests')
        op.drop_index(op.f('ix_signature_requests_status'), table_name='signature_requests')
        op.drop_index(op.f('ix_signature_requests_signed_document_cid'), table_name='signature_requests')
        op.drop_index(op.f('ix_signature_requests_sha256_signed'), table_name='signature_requests')
        op.drop_index(op.f('ix_signature_requests_expiration'), table_name='signature_requests')
        op.drop_index(op.f('ix_signature_requests_document_filename'), table_name='signature_requests')
        op.drop_table('signature_requests')
    # ### end Alembic commands ###
