"""add_status_to_templates

Revision ID: 90873432a2b5
Revises: d79d61c48330
Create Date: 2026-07-05 02:44:55.479567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90873432a2b5'
down_revision: Union[str, Sequence[str], None] = 'd79d61c48330'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('templates', sa.Column('status', sa.String(), nullable=False, server_default='approved'))
    op.add_column('templates', sa.Column('comments', sa.String(), nullable=True))
    op.add_column('templates', sa.Column('uploaded_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'templates', 'users', ['uploaded_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'templates', type_='foreignkey')
    op.drop_column('templates', 'uploaded_by_id')
    op.drop_column('templates', 'comments')
    op.drop_column('templates', 'status')
    # ### end Alembic commands ###
