"""add_ipns_and_webhooks

Revision ID: 95e503014105
Revises: fc581ed63cc7
Create Date: 2026-05-21 17:40:48.271626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '95e503014105'
down_revision: Union[str, Sequence[str], None] = 'fc581ed63cc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ipns_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ipns_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('current_cid', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_published_at', sa.DateTime(), nullable=True),
    sa.Column('last_republished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ipns_keys_ipns_id'), 'ipns_keys', ['ipns_id'], unique=False)
    op.create_index(op.f('ix_ipns_keys_key_name'), 'ipns_keys', ['key_name'], unique=True)
    op.create_index(op.f('ix_ipns_keys_user_id'), 'ipns_keys', ['user_id'], unique=False)
    op.create_table('webhook_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('secret', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('events', sa.JSON(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_triggered_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_subscriptions_name'), 'webhook_subscriptions', ['name'], unique=False)
    op.create_index(op.f('ix_webhook_subscriptions_user_id'), 'webhook_subscriptions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webhook_subscriptions_user_id'), table_name='webhook_subscriptions')
    op.drop_index(op.f('ix_webhook_subscriptions_name'), table_name='webhook_subscriptions')
    op.drop_table('webhook_subscriptions')
    op.drop_index(op.f('ix_ipns_keys_user_id'), table_name='ipns_keys')
    op.drop_index(op.f('ix_ipns_keys_key_name'), table_name='ipns_keys')
    op.drop_index(op.f('ix_ipns_keys_ipns_id'), table_name='ipns_keys')
    op.drop_table('ipns_keys')
    # ### end Alembic commands ###
