"""check_changes

Revision ID: 9bc549a84d2e
Revises: 8061bfc7f356
Create Date: 2026-07-15 20:21:44.209189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector

# revision identifiers, used by Alembic.
revision: str = '9bc549a84d2e'
down_revision: Union[str, Sequence[str], None] = '8061bfc7f356'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("TRUNCATE TABLE legal_knowledge_chunks CASCADE;")
    op.drop_index(op.f('ix_cryptpad_sessions_filename'), table_name='cryptpad_sessions')
    op.drop_index(op.f('ix_cryptpad_sessions_is_active'), table_name='cryptpad_sessions')
    op.drop_table('cryptpad_sessions')
    op.alter_column('legal_knowledge_chunks', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=3072),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               existing_nullable=False)
    op.create_index('hnsw_legal_embedding_idx', 'legal_knowledge_chunks', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': 16, 'ef_construction': 64})
    op.alter_column('user_documents', 'is_collaborative',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_documents', 'is_collaborative',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_index('hnsw_legal_embedding_idx', table_name='legal_knowledge_chunks', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': 16, 'ef_construction': 64})
    op.alter_column('legal_knowledge_chunks', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=3072),
               existing_nullable=False)
    op.create_table('cryptpad_sessions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('cryptpad_url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('cryptpad_key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('cryptpad_sessions_pkey'))
    )
    op.create_index(op.f('ix_cryptpad_sessions_is_active'), 'cryptpad_sessions', ['is_active'], unique=False)
    op.create_index(op.f('ix_cryptpad_sessions_filename'), 'cryptpad_sessions', ['filename'], unique=True)
    # ### end Alembic commands ###
