"""check_changes

Revision ID: ab8b9556bc8e
Revises: 3f48a1c92da1
Create Date: 2026-07-03 15:56:41.084208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab8b9556bc8e'
down_revision: Union[str, Sequence[str], None] = '3f48a1c92da1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Actualizar registros existentes que tengan classification en NULL para evitar fallos de integridad
    op.execute("UPDATE signature_requests SET classification = 'chain_of_custody' WHERE classification IS NULL")
    op.alter_column('signature_requests', 'classification',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('signature_requests', 'classification',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###
