"""add_approval_fields_to_user_documents

Revision ID: d79d61c48330
Revises: 114a376ae4e2
Create Date: 2026-07-05 01:55:28.575706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd79d61c48330'
down_revision: Union[str, Sequence[str], None] = '114a376ae4e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_documents', sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.execute("UPDATE user_documents SET status = 'draft' WHERE status IS NULL")
    op.alter_column('user_documents', 'status', nullable=False)
    
    op.add_column('user_documents', sa.Column('comments', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user_documents', sa.Column('reviewed_by_id', sa.Integer(), nullable=True))
    op.add_column('user_documents', sa.Column('reviewed_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_user_documents_status'), 'user_documents', ['status'], unique=False)
    op.create_foreign_key(None, 'user_documents', 'users', ['reviewed_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_documents', type_='foreignkey')
    op.drop_index(op.f('ix_user_documents_status'), table_name='user_documents')
    op.drop_column('user_documents', 'reviewed_at')
    op.drop_column('user_documents', 'reviewed_by_id')
    op.drop_column('user_documents', 'comments')
    op.drop_column('user_documents', 'status')
    # ### end Alembic commands ###
