"""add_ipfs_audits_and_logs

Revision ID: f4a24a0541f9
Revises: 4f489ff09de7
Create Date: 2026-05-19 15:33:49.352648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f4a24a0541f9'
down_revision: Union[str, Sequence[str], None] = '4f489ff09de7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_access_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ipfs_cid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('accessed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_access_logs_action'), 'document_access_logs', ['action'], unique=False)
    op.create_index(op.f('ix_document_access_logs_ipfs_cid'), 'document_access_logs', ['ipfs_cid'], unique=False)
    op.create_index(op.f('ix_document_access_logs_user_id'), 'document_access_logs', ['user_id'], unique=False)
    op.create_table('ipfs_audits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ipfs_cid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('classification', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('document_ids', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ipfs_audits_ipfs_cid'), 'ipfs_audits', ['ipfs_cid'], unique=True)
    op.create_index(op.f('ix_ipfs_audits_name'), 'ipfs_audits', ['name'], unique=False)
    
    op.alter_column('appointments', 'appointment_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sqlmodel.sql.sqltypes.AutoString(length=50),
               existing_nullable=False)
    op.alter_column('appointments', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sqlmodel.sql.sqltypes.AutoString(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointments', 'status',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('appointments', 'appointment_type',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
               
    op.drop_index(op.f('ix_ipfs_audits_name'), table_name='ipfs_audits')
    op.drop_index(op.f('ix_ipfs_audits_ipfs_cid'), table_name='ipfs_audits')
    op.drop_table('ipfs_audits')
    op.drop_index(op.f('ix_document_access_logs_user_id'), table_name='document_access_logs')
    op.drop_index(op.f('ix_document_access_logs_ipfs_cid'), table_name='document_access_logs')
    op.drop_index(op.f('ix_document_access_logs_action'), table_name='document_access_logs')
    op.drop_table('document_access_logs')
    # ### end Alembic commands ###
