"""add_ipfs_cid_original

Revision ID: fc581ed63cc7
Revises: f4a24a0541f9
Create Date: 2026-05-21 16:41:28.492792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc581ed63cc7'
down_revision: Union[str, Sequence[str], None] = 'f4a24a0541f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents_ipfs', sa.Column('ipfs_cid_original', sa.String(), nullable=True))
    op.create_index(op.f('ix_documents_ipfs_ipfs_cid_original'), 'documents_ipfs', ['ipfs_cid_original'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_ipfs_ipfs_cid_original'), table_name='documents_ipfs')
    op.drop_column('documents_ipfs', 'ipfs_cid_original')
    # ### end Alembic commands ###
