"""add_classification_to_signature_request

Revision ID: fe558c878bb6
Revises: 16c6dffeaf93
Create Date: 2026-06-19 22:59:25.280113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


from sqlalchemy.engine import reflection

# revision identifiers, used by Alembic.
revision: str = 'fe558c878bb6'
down_revision: Union[str, Sequence[str], None] = '16c6dffeaf93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspect_obj = reflection.Inspector.from_engine(bind)
    tables = inspect_obj.get_table_names()

    if 'signature_requests' in tables:
        columns = [c['name'] for c in inspect_obj.get_columns('signature_requests')]
        if 'classification' not in columns:
            op.add_column('signature_requests', sa.Column('classification', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
            op.create_index(op.f('ix_signature_requests_classification'), 'signature_requests', ['classification'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspect_obj = reflection.Inspector.from_engine(bind)
    tables = inspect_obj.get_table_names()

    if 'signature_requests' in tables:
        columns = [c['name'] for c in inspect_obj.get_columns('signature_requests')]
        if 'classification' in columns:
            op.drop_index(op.f('ix_signature_requests_classification'), table_name='signature_requests')
            op.drop_column('signature_requests', 'classification')
    # ### end Alembic commands ###
